### ISSUE TITLE
Request for license attribution - Skyra Project/Skyra

### ISSUE THREAD

**Issue by Favna** [RTByte/rtbyte#457]
Hello there,

You may know me as one of the core maintainers / co-owners of the Skyra discord bot (https://github.com/skyra-project/skyra) and core maintainer to the Sapphire project

I was recently made aware of this repository through a contributor to the Sapphire Project who was gracious enough to suggest adding this project to our list of recommended examples (https://github.com/sapphiredev/sapphire-slashies/pull/31). As things go with these kind of processes it is my job to vet the suggestions by looking through the repository in question.

While doing just this, I noticed that many things of this repository are very strongly based on that of Skyra, clearly showing that the basic ideas are generally copied over.

Examples are:
- The exact setup of the files on the root
- The commit message that is used for Crowdin
- The general structure of the README
  - Logo and badges centered followed by Development -> Requirements & Options and then a header `A note regarding self-hosting ...`
- https://github.com/RTByte/rtbyte/blob/master/.vscode/settings.json referencing the `.yarn` folder for Yarn v3, despite this project using NPM as package manager.
- https://github.com/RTByte/rtbyte/blob/master/src/arguments/channelName.ts and other files being a 1:1 copy

**That all said, I would like to formally ask you to add proper license attribution to this repository. Failure to do so will force me to issue a DMCA takedown notice through https://support.github.com/contact/dmca-takedown**. Please comply to this request _**within 7 standard days of this issue being created**_

You can add proper license attribution by adding a file called `THIRD_PARTY_LICENSES` to the root of your project with the **full** content of https://github.com/skyra-project/skyra/blob/main/LICENSE.

**Comment by rasmusgerdin** [comment]
Hey @Favna, 

I decided to sort this out right away instead of later this weekend as I mentioned during on conversation on Discord. 

I've made a couple changes (shown above) that should cover all the third-party attributions in the code. Please let me know if I missed anything, or if any further changes would need to be made. I also took the opportunity to remove the unnecessary inclusion of `.yarn` in https://github.com/RTByte/rtbyte/blob/master/.vscode/settings.json - thanks for pointing that out!

With the content of the `README` being different but still following a similar outline and layout, I'll definitely take the time to rewrite it over the next few weeks in good faith. This may however take some time - hope that's alright.

Apologies again for not already having proper license attribution! Thanks for submitting this right away and for being understanding during our interaction over Discord.
